--소재사용
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	   GET diagnostics condition 1
	    @rs = RETURNED_SQLSTATE, @mt = MESSAGE_TEXT;
		INSERT INTO tb_loghis (ERRCODE, ERRMESSAGE, PROCEDURE_NAME, ERRTIME) VALUES(@rs, @mt, 'SP_DEL_TBMACUSEHIS', NOW());
	END;
	
	START TRANSACTION;
	
	SELECT @USEQTY := useqty, @ITMCD := ITMCD FROM tb_macusehis WHERE SEQNO=_SEQNO;
	
	DELETE FROM tb_macusehis WHERE SEQNO = _SEQNO;
	
	INSERT INTO tb_inventwrk (EVTDATE, ITMCD, WHOQTY, DEVQTY, REMARK, REGDATIME, EDTDATIME) VALUES (DATE_FORMAT(NOW(),'%Y-%m-%d'),@ITMCD,0, @USEQTY  * (-1),'',NOW(),NOW());
		
	SELECT CONCAT('D','|',_SEQNO) AS UPDATECHECK;
	
	COMMIT;
	
END


--입고등록
BEGIN
	
	DECLARE TMP_WHSQTY NUMERIC(15,2);
	DECLARE TMP_EVTDATE VARCHAR(10);
	DECLARE TMP_ITMCD VARCHAR(20);
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	   GET diagnostics condition 1
	    @rs = RETURNED_SQLSTATE, @mt = MESSAGE_TEXT;
		INSERT INTO tb_loghis (ERRCODE, ERRMESSAGE, PROCEDURE_NAME, ERRTIME) VALUES(@rs, @mt, 'SP_DEL_TBPDTWHSHIS', NOW());
	END;
	
	START TRANSACTION;
	
	SET TMP_WHSQTY = 0;
	
	SELECT WHSQTY, EVTDATE, ITMCD
	FROM TB_PDTWHSHIS
	WHERE SEQNO = _SEQNO
	INTO TMP_WHSQTY, TMP_EVTDATE, TMP_ITMCD;
	
	SELECT @WHSQTY := WHSQTY ,@CSTCD := CSTCD, @ITMCD := ITMCD FROM tb_pdtwhshis WHERE SEQNO=_SEQNO;
	
	DELETE FROM TB_PDTWHSHIS WHERE SEQNO = _SEQNO;
	
	INSERT INTO tb_inventwrk (EVTDATE, ITMCD, WHOQTY, DEVQTY, REMARK, REGDATIME, EDTDATIME) VALUES (DATE_FORMAT(NOW(),'%Y-%m-%d'),@ITMCD,@WHSQTY, 0,'',NOW(),NOW());
	
	IF(EXISTS(SELECT EVTDATE FROM tb_inventwrk WHERE EVTDATE = TMP_EVTDATE AND ITMCD = TMP_ITMCD)) THEN
		UPDATE tb_inventwrk SET WHOQTY = COALESCE(WHOQTY, 0) - TMP_WHSQTY
								WHERE EVTDATE = TMP_EVTDATE AND ITMCD = TMP_ITMCD;
	END IF;
	
	SELECT CONCAT('D','|',_SEQNO) AS UPDATECHECK;
	
	COMMIT;
	
END