--저장프로시저--

USE [THINMESFK]
GO
/****** Object:  StoredProcedure [dbo].[SP_GET_TEST]    Script Date: 2023-01-12 오전 9:10:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_GET_TEST]
	-- @UNICD VARCHAR(20)
AS
BEGIN	
	--SET @UNICD = UPPER(@UNICD)
	
	SELECT U.UNICD FROM TB_UNIMST2INFO U 
	WHERE U.CLASS = 'F' 
	--SELECT UNICD FROM TB_UNIMST2INFO WHERE UNICD = @UNICD
	
	
END

--리포트 프로시저--
USE [THINMESFK]
GO
/****** Object:  StoredProcedure [dbo].[SP_GET_TEST]    Script Date: 2023-01-12 오전 9:10:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_GET_TEST_REPORT]
	 @UNICD VARCHAR(100)
AS
BEGIN	

	SELECT UNICD FROM TB_UNIMST2INFO 
	WHERE CLASS = 'F' 
	AND UNICD IN (SELECT * FROM STRING_SPLIT(@UNICD,','))
	
END