SELECT * FROM 
(
    select 
        TABLE_NAME, 
        ORDINAL_POSITION , 
        COLUMN_NAME,
        DATA_TYPE  , 
        CHARACTER_MAXIMUM_LENGTH,
        IS_NULLABLE,
        COLUMN_DEFAULT
        TABKE_CATALOG
    from INFORMATION_SCHEMA.COLUMNS
) A
 LEFT OUTER JOIN 
( 
    SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE  
) B 
ON A.COLUMN_NAME = B.COLUMN_NAME 
AND A.TABLE_NAME = B.TABLE_NAME
ORDER BY A.TABLE_NAME,A.ORDINAL_POSITION