CREATE TABLE `tb_dptmstinfo` (
	`UNTCD` VARCHAR(5) NOT NULL,
	`DPTCD` VARCHAR(5) NOT NULL,
	`DPTNM` VARCHAR(50) NULL DEFAULT NULL,
	`INVMAG` VARCHAR(1) NULL DEFAULT NULL,
	`BUDMAG` VARCHAR(1) NULL DEFAULT NULL,
	`REMARK` VARCHAR(100) NULL DEFAULT NULL,
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL,
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL,
	`REGDATIME` DATETIME NULL DEFAULT NULL,
	`EDTDATIME` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`UNTCD`, `DPTCD`)
)
COMMENT='부서정보'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `tb_3dpmtnhis` (
	`SEQNO` VARCHAR(11) NULL DEFAULT NULL COMMENT '년월일순번',
	`MACCD` VARCHAR(20) NULL DEFAULT NULL COMMENT '자산관리번호',
	`EVTDATE` VARCHAR(10) NULL DEFAULT NULL COMMENT '날짜(구축일자)',
	`MTNTERM` VARCHAR(100) NULL DEFAULT NULL COMMENT '유지보수기간',
	`MTNAMT` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '유지보수비용',
	`IPTDATE` VARCHAR(10) NULL DEFAULT NULL COMMENT '최근점검일자',
	`REMARK` VARCHAR(300) NULL DEFAULT NULL COMMENT '비고',
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일'
)
COMMENT='3D프린터유지보수'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_3dsmtnhis` (
	`SEQNO` VARCHAR(11) NOT NULL COMMENT '년월일순번',
	`MACCD` VARCHAR(20) NULL DEFAULT NULL COMMENT '자산관리번호(S/W)',
	`EVTDATE` VARCHAR(10) NULL DEFAULT NULL COMMENT '날짜(구축일자)',
	`MTNTERM` VARCHAR(100) NULL DEFAULT NULL COMMENT '유지보수기간',
	`MTNAMT` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '유지보수비용',
	`REMARK` VARCHAR(300) NULL DEFAULT NULL COMMENT '비고',
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`SEQNO`)
)
COMMENT='S/W 유지보수'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_cstmstinfo` (
	`CSTCD` VARCHAR(20) NOT NULL COMMENT '거래선코드',
	`CSTNM` VARCHAR(100) NULL DEFAULT NULL COMMENT '거래선명',
	`CSTCEO` VARCHAR(50) NULL DEFAULT NULL COMMENT '대표자명',
	`BIZNO` VARCHAR(12) NULL DEFAULT NULL COMMENT '사업자번호',
	`CSTKIND` VARCHAR(50) NULL DEFAULT NULL COMMENT '업태',
	`CSTITEM` VARCHAR(50) NULL DEFAULT NULL COMMENT '종목',
	`TELNO` VARCHAR(20) NULL DEFAULT NULL COMMENT '전화번호',
	`FAXNO` VARCHAR(20) NULL DEFAULT NULL COMMENT 'FAX번호',
	`ZIPNO` VARCHAR(7) NULL DEFAULT NULL COMMENT '우편번호',
	`ADDR1` VARCHAR(200) NULL DEFAULT NULL COMMENT '주소',
	`ADDR2` VARCHAR(100) NULL DEFAULT NULL COMMENT '상세주소',
	`CHGNAME` VARCHAR(30) NULL DEFAULT NULL,
	`CHGTEL` VARCHAR(30) NULL DEFAULT NULL,
	`CHGMAIL` VARCHAR(30) NULL DEFAULT NULL,
	`REMARK` VARCHAR(300) NULL DEFAULT NULL,
	`USETYPE` VARCHAR(1) NULL DEFAULT NULL COMMENT '사용구분',
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`CSTCD`)
)
COMMENT='거래처정보'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_inventwrk` (
	`EVTDATE` VARCHAR(10) NULL DEFAULT NULL COMMENT '거래일자(생산일)',
	`ITMCD` VARCHAR(20) NULL DEFAULT NULL COMMENT '품목코드',
	`WHOQTY` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '입고수량',
	`DEVQTY` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '출고수량',
	`REMARK` VARCHAR(100) NULL DEFAULT NULL COMMENT '비고',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일'
)
COMMENT='재고내역'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_itmmstinfo` (
	`ITMCD` VARCHAR(20) NOT NULL COMMENT '품목코드(STYLE NO)',
	`ITMNM` VARCHAR(100) NULL DEFAULT NULL COMMENT '품목명',
	`ITMSIZE` VARCHAR(100) NULL DEFAULT NULL COMMENT '규격',
	`STDUNIT` VARCHAR(10) NULL DEFAULT NULL COMMENT '단위',
	`WEIGHT` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '중량',
	`BUYCOST` INT(11) NULL DEFAULT NULL COMMENT '구매단가',
	`REMARK` VARCHAR(300) NULL DEFAULT NULL COMMENT '비고',
	`MACCD` VARCHAR(300) NULL DEFAULT NULL COMMENT '자산관리번호',
	`USETYPE` VARCHAR(1) NULL DEFAULT NULL COMMENT '사용구분',
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`ITMCD`)
)
COMMENT='품목정보'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_loghis` (
	`CNTID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ERRCODE` VARCHAR(100) NULL DEFAULT NULL,
	`ERRMESSAGE` TEXT NULL DEFAULT NULL,
	`PROCEDURE_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`ERRTIME` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`CNTID`)
)
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=106
;

CREATE TABLE `tb_macmstinfo` (
	`MACCD` VARCHAR(20) NOT NULL COMMENT '자산관리번호',
	`MACTYPE` VARCHAR(20) NULL DEFAULT '3D프린터' COMMENT '장비종류 / 3D프린터,후처리장비, S/W',
	`MACNM` VARCHAR(100) NULL DEFAULT NULL COMMENT '장비명',
	`MODELNM` VARCHAR(100) NULL DEFAULT NULL COMMENT '모델명',
	`MARKER` VARCHAR(100) NULL DEFAULT NULL COMMENT '제조처',
	`MATTYPE` VARCHAR(10) NULL DEFAULT NULL COMMENT '소재구분 / ‘-‘, 금속, 비금속',
	`BUYDATE` VARCHAR(10) NULL DEFAULT '-' COMMENT '구입일',
	`BUYMONEY` INT(11) NULL DEFAULT NULL,
	`MACCHAGE` INT(11) NULL DEFAULT NULL,
	`MATCHARGE` INT(11) NULL DEFAULT NULL,
	`REMARK` VARCHAR(300) NULL DEFAULT NULL COMMENT 'REMARK',
	`USETYPE` VARCHAR(1) NULL DEFAULT 'Y' COMMENT '사용구분 / Y,N',
	`REGUSER` VARCHAR(20) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(20) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`MACCD`)
)
COMMENT='자산정보'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_macplnhis` (
	`SEQNO` VARCHAR(11) NOT NULL,
	`MACCD` VARCHAR(10) NULL DEFAULT NULL,
	`CSTNM` VARCHAR(100) NULL DEFAULT NULL,
	`BIZNO` VARCHAR(12) NULL DEFAULT NULL,
	`STADATE` VARCHAR(10) NULL DEFAULT NULL,
	`FSHDATE` VARCHAR(10) NULL DEFAULT NULL,
	`USAGETIME` VARCHAR(10) NULL DEFAULT NULL,
	`USAGEFEE` DECIMAL(15,2) NULL DEFAULT NULL,
	`SAMPLE` VARCHAR(20) NULL DEFAULT NULL,
	`PURPOSE` VARCHAR(300) NULL DEFAULT NULL,
	`DOCIMG` VARCHAR(100) NULL DEFAULT NULL,
	`USEQTY` DECIMAL(15,2) NULL DEFAULT NULL,
	`REMARK` VARCHAR(300) NULL DEFAULT NULL,
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL,
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL,
	`REGDATIME` DATETIME NULL DEFAULT NULL,
	`EDTDATIME` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`SEQNO`)
)
COMMENT='자산유지보수'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_macusehis` (
	`SEQNO` VARCHAR(11) NOT NULL COMMENT '년월일순번',
	`ITMCD` VARCHAR(20) NULL DEFAULT NULL COMMENT '품목코드',
	`USEQTY` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '소재사용량',
	`REMARK` VARCHAR(300) NULL DEFAULT NULL COMMENT '비고',
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`SEQNO`)
)
COMMENT='소재사용내역'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_pdtwhshis` (
	`SEQNO` VARCHAR(11) NOT NULL COMMENT '입고번호',
	`EVTDATE` VARCHAR(10) NULL DEFAULT NULL COMMENT '입고일',
	`CSTCD` VARCHAR(20) NULL DEFAULT NULL COMMENT '거래선코드',
	`ITMCD` VARCHAR(20) NULL DEFAULT NULL COMMENT '품목코드',
	`WHSQTY` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '구매량',
	`REMARK` VARCHAR(300) NULL DEFAULT NULL COMMENT '비고',
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`SEQNO`)
)
COMMENT='입고내역'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_untmstinfo` (
	`UNTCD` VARCHAR(5) NOT NULL,
	`UNTNM` VARCHAR(30) NULL DEFAULT NULL,
	`UNTCEO` VARCHAR(20) NULL DEFAULT NULL,
	`BIZNO` VARCHAR(12) NULL DEFAULT NULL,
	`CORPNO` VARCHAR(20) NULL DEFAULT NULL,
	`BIZITEM` VARCHAR(30) NULL DEFAULT NULL,
	`BIZKIND` VARCHAR(30) NULL DEFAULT NULL,
	`TELNO` VARCHAR(20) NULL DEFAULT NULL,
	`FAXNO` VARCHAR(20) NULL DEFAULT NULL,
	`ZIPNO` VARCHAR(7) NULL DEFAULT NULL,
	`ADDRESS` VARCHAR(200) NULL DEFAULT NULL,
	`UNTTAXID` VARCHAR(10) NULL DEFAULT NULL,
	`VATTYPE` VARCHAR(4) NULL DEFAULT NULL,
	`TAXOFFICECD` VARCHAR(10) NULL DEFAULT NULL,
	`TAXOFFICE` VARCHAR(14) NULL DEFAULT NULL,
	`TAXCITYWARD` VARCHAR(20) NULL DEFAULT NULL,
	`ACCDATE` VARCHAR(10) NULL DEFAULT NULL,
	`REMARK` VARCHAR(100) NULL DEFAULT NULL,
	`UNTSTAMP` MEDIUMBLOB NULL DEFAULT NULL,
	`UNTMARK` BLOB NULL DEFAULT NULL,
	`REGUSER` VARCHAR(10) NULL DEFAULT NULL,
	`EDTUSER` VARCHAR(10) NULL DEFAULT NULL,
	`REGDATIME` DATETIME NULL DEFAULT NULL,
	`EDTDATIME` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`UNTCD`)
)
COMMENT='사업장 정보'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tb_usermstinfo` (
	`UNTCD` VARCHAR(20) NOT NULL COMMENT '사업장',
	`USERID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
	`USERPW` VARCHAR(60) NULL DEFAULT NULL COMMENT '사용자 PW',
	`EMPNM` VARCHAR(50) NULL DEFAULT NULL COMMENT '사원명',
	`REMARK` VARCHAR(100) NULL DEFAULT NULL COMMENT '비고',
	`REGUSER` VARCHAR(50) NULL DEFAULT NULL COMMENT '등록담당자',
	`EDTUSER` VARCHAR(50) NULL DEFAULT NULL COMMENT '수정담당자',
	`REGDATIME` DATETIME NULL DEFAULT NULL COMMENT '등록일',
	`EDTDATIME` DATETIME NULL DEFAULT NULL COMMENT '수정일',
	PRIMARY KEY (`UNTCD`, `USERID`)
)
COMMENT='계정정보'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;
